name: Unanimously Approved

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  statuses: write
  pull-requests: read

jobs:
  unanimously-approved:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: snow-actions/unanimously-approved@v3.0.0